In [1]:
data1 =  [6, 7.5, 9, 0 ,1]

In [3]:
import numpy as np

In [4]:
arr1 = np.array(data1)

In [5]:
arr1

array([6. , 7.5, 9. , 0. , 1. ])

In [6]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2,3,2))

array([[[1.12140557e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [3.14573925e+097, 9.04729232e-067]],

       [[8.38306083e+165, 2.44700085e-056],
        [6.87067803e-038, 2.27160561e+184],
        [4.98318124e-037, 2.27111451e+184]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
np.ones_like((3,3))

array([1, 1])

In [22]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [24]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [25]:
np.eye(2, k = 1)

array([[0., 1.],
       [0., 0.]])

In [26]:
np.eye(3, k = 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr1 = np.array([1,2,3], dtype = np.float64)

In [28]:
arr2 = np.array([1,2,3], dtype = np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1,2,3,4,5])

In [32]:
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr

array([1., 2., 3., 4., 5.])

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
arr = np.array([3.7, -1.2, -3.6, 0.5, 12.9, 10.1])

In [37]:
arr

array([ 3.7, -1.2, -3.6,  0.5, 12.9, 10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -3,  0, 12, 10], dtype=int32)

In [44]:
numeric_strings = np.array(["1.24", "-9.6", "42"], dtype = np.str_)

In [45]:
numeric_strings.astype(float)

array([ 1.24, -9.6 , 42.  ])

In [46]:
arr = np.array([[1.,2.,3.], [3.,5.,6.]])

In [47]:
arr

array([[1., 2., 3.],
       [3., 5., 6.]])

In [48]:
arr * arr

array([[ 1.,  4.,  9.],
       [ 9., 25., 36.]])

In [49]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.33333333, 0.2       , 0.16666667]])

In [51]:
arr ** 2

array([[ 1.,  4.,  9.],
       [ 9., 25., 36.]])

In [53]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [54]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [55]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [56]:
arr = np.array(10)

In [57]:
arr

array(10)

In [58]:
arr = np.arange(10)

In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr[5]

np.int64(5)

In [62]:
arr[5:8]

array([5, 6, 7])

In [63]:
arr[5:8] =- 12

In [64]:
arr

array([  0,   1,   2,   3,   4, -12, -12, -12,   8,   9])

In [65]:
arr_slice = arr[5:8]

In [66]:
arr_slice

array([-12, -12, -12])