In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5:8] = 12

In [5]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [6]:
arr_slice = arr[5:8]

In [7]:
arr_slice

array([12, 12, 12])

In [8]:
arr_slice[1] = 12345

In [9]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [10]:
arr_slice[:] = 64

In [11]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [12]:
arr[5:8].copy

<function ndarray.copy(order='C')>

In [13]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [14]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
arr2d[2]

array([7, 8, 9])

In [16]:
arr2d[0][2]

np.int64(3)

In [17]:
arr2d[0, 2]

np.int64(3)

In [19]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [20]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
old_values = arr3d[0].copy()

In [23]:
arr3d[0] = 42

In [24]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr3d[0] = old_values

In [26]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[1,0]

array([7, 8, 9])

In [28]:
x = arr3d[1]

In [29]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [30]:
x[0]

array([7, 8, 9])