In [1]:
import numpy as np

In [2]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [6]:
arr2d[:2, 2]

array([3, 6])

In [7]:
arr2d[:2,1]

array([2, 5])

In [8]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [9]:
arr2d[:2,1:] = 0

In [10]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [11]:
arr2d[2].shape

(3,)

In [13]:
arr2d[:,1:]

array([[0, 0],
       [0, 0],
       [8, 9]])

In [14]:
arr2d[:,:2]

array([[1, 0],
       [4, 0],
       [7, 8]])

In [15]:
arr2d[:0, 0:1]

array([], shape=(0, 1), dtype=int64)

In [16]:
arr2d[:1, :1]

array([[1]])

In [17]:
arr2d[:1,:]

array([[1, 0, 0]])

In [18]:
arr2d[1:, :]

array([[4, 0, 0],
       [7, 8, 9]])

In [19]:
arr2d[2:, :]

array([[7, 8, 9]])

In [20]:
arr2d[2:, 1:]

array([[8, 9]])

In [21]:
names = np.array(["bob", "joe", "will", "bob", "will", "joe", "joe"])

In [22]:
data = np.array([[4,7],[0,2], [-5,6],[0,0],[1,2],[-12,-4],[3,4]])

In [23]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [24]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [25]:
names == "bob"

array([ True, False, False,  True, False, False, False])

In [27]:
data[names == "bob"]

array([[4, 7],
       [0, 0]])

In [28]:
data[4:, 1:]

array([[ 2],
       [-4],
       [ 4]])

In [29]:
data[names == "bob", 1:]

array([[7],
       [0]])

In [30]:
data[names == "bob", 1]

array([7, 0])

In [31]:
names != "bob"

array([False,  True,  True, False,  True,  True,  True])

In [32]:
~(names == "bob")

array([False,  True,  True, False,  True,  True,  True])

In [33]:
data[~(names == "bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [34]:
cond = names == "bob"

In [35]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [37]:
mask = (names == "bob") | (names == "will")

In [38]:
mask

array([ True, False,  True,  True,  True, False, False])

In [39]:
 data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [40]:
data[data < 0] = 0

In [41]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [44]:
data[~(names == "joe")] = 7

In [45]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [47]:
arr = np.zeros((8,4))

In [48]:
for i in range(8):
    arr[i] = i

In [49]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [50]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [51]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [52]:
arr = np.arange(32).reshape((8,4))

In [53]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [54]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [55]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [59]:
arr[[0,3,6,4]][:, [-1,-2,-3,-4]]

array([[ 3,  2,  1,  0],
       [15, 14, 13, 12],
       [27, 26, 25, 24],
       [19, 18, 17, 16]])

In [60]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [61]:
arr[[1,5,7,2],[0,3,1,2]] = 0

In [62]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [63]:
arr = np.arange(15).reshape((3,5))

In [64]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [66]:
arr = np.array([[0,1,0],[1,2,-2],[6,3,2],[-1,0,-1],[1,0,1]])

In [67]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [68]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [69]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [70]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [71]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [72]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])