In [1]:
import numpy as np

In [3]:
samples = np.random.standard_normal(size = (4,4))

In [4]:
samples

array([[ 1.40252146,  0.74100056, -0.80577213,  1.19492922],
       [ 0.45618716, -1.03775372, -0.22937419,  0.99964789],
       [-0.90488922,  1.29757651,  0.26393254, -1.18750424],
       [-1.0656754 , -0.70187441,  0.30949125,  0.05526402]])

In [5]:
from random import normalvariate

In [6]:
N = 1000000

In [8]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

1.07 s ± 30.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
rng = np.random.default_rng(seed = 12345)

In [10]:
data = rng.standard_normal((2,3))

In [11]:
type(rng)

numpy.random._generator.Generator

In [14]:
a

<bound method RandomState.permutation of RandomState(MT19937) at 0x264CD381340>

In [15]:
rng.permutation(10)

array([0, 8, 3, 7, 2, 6, 9, 5, 4, 1])

In [16]:
rng.uniform(0,10,5)

array([8.86479919, 6.974535  , 3.26472864, 7.33928163, 2.20134956])

In [17]:
arr = np.arange(10)

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [21]:
x = rng.standard_normal(8)

In [22]:
y = rng.standard_normal(8)

In [23]:
x

array([ 1.32229806, -0.29969852,  0.90291934, -1.62158273, -0.15818926,
        0.44948393, -1.34360107, -0.08168759])

In [24]:
y

array([ 1.72473993,  2.61815943,  0.77736134,  0.8286332 , -0.95898831,
       -1.20938829, -1.41229201,  0.54154683])

In [25]:
np.maximum(x,y)

array([ 1.72473993,  2.61815943,  0.90291934,  0.8286332 , -0.15818926,
        0.44948393, -1.34360107,  0.54154683])

In [26]:
arr = rng.standard_normal(7) * 5

In [27]:
arr

array([ 3.75969698, -3.2938016 , -6.14337493,  1.28778884,  1.56451459,
       -0.65405845,  6.3499156 ])

In [28]:
remainder, whole_part = np.modf(arr)

In [29]:
remainder

array([ 0.75969698, -0.2938016 , -0.14337493,  0.28778884,  0.56451459,
       -0.65405845,  0.3499156 ])

In [30]:
whole_part

array([ 3., -3., -6.,  1.,  1., -0.,  6.])

In [31]:
arr 

array([ 3.75969698, -3.2938016 , -6.14337493,  1.28778884,  1.56451459,
       -0.65405845,  6.3499156 ])

In [32]:
out = np.zeros_like(arr)

In [33]:
np.add(arr, 1)

array([ 4.75969698, -2.2938016 , -5.14337493,  2.28778884,  2.56451459,
        0.34594155,  7.3499156 ])

In [34]:
np.add(arr, 1, out = out)

array([ 4.75969698, -2.2938016 , -5.14337493,  2.28778884,  2.56451459,
        0.34594155,  7.3499156 ])

In [35]:
out

array([ 4.75969698, -2.2938016 , -5.14337493,  2.28778884,  2.56451459,
        0.34594155,  7.3499156 ])

In [36]:
points = np.arange(-5, 5, 0.01)

In [37]:
xs, ys = np.meshgrid(points, points)

In [38]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]],
      shape=(1000, 1000))

In [41]:
z = np.sqrt(xs ** 2+ ys **2)

In [42]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]], shape=(1000, 1000))

In [44]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])

In [45]:
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [46]:
cond = np.array([True, False, True, True, False])

In [48]:
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]

In [49]:
result 

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [50]:
result = np.where(cond, xarr, yarr)

In [51]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [52]:
arr = rng.standard_normal((4,4))

In [53]:
arr

array([[-0.09296246, -0.06615089, -1.10821447,  0.13595685],
       [ 1.34707776,  0.06114402,  0.0709146 ,  0.43365454],
       [ 0.27748366,  0.53025239,  0.53672097,  0.61835001],
       [-0.79501746,  0.30003095, -1.60270159,  0.26679883]])

In [54]:
arr > 0

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True]])

In [55]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [-2,  2, -2,  2]])

In [57]:
np.where(arr > 0, 2, arr)

array([[-0.09296246, -0.06615089, -1.10821447,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [-0.79501746,  2.        , -1.60270159,  2.        ]])

In [58]:
arr = rng.standard_normal((5,4))

In [59]:
arr

array([[-1.26162378, -0.07127081,  0.47404973, -0.41485376],
       [ 0.0977165 , -1.64041784, -0.85725882,  0.68828179],
       [-1.15452958,  0.65045239, -1.38835995, -0.90738246],
       [-1.09542531,  0.00714569,  0.5343599 , -1.06580785],
       [-0.18147274,  1.6219518 , -0.31739195, -0.81581497]])

In [60]:
arr.mean()

np.float64(-0.35488260029815666)

In [61]:
np.mean(arr)

np.float64(-0.35488260029815666)

In [62]:
arr.sum()

np.float64(-7.097652005963133)

In [63]:
arr.mean(axis = 0)

array([-0.71906698,  0.11357225, -0.31092022, -0.50311545])

In [64]:
arr.sum(axis = 1)

array([-1.27369862, -1.71167837, -2.7998196 , -1.61972756,  0.30727215])

In [65]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr.cumsum(axis = 0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [68]:
arr.cumsum(axis = 1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [69]:
arr = rng.standard_normal(100)

In [70]:
(arr > 0).sum()

np.int64(52)

In [71]:
(arr <= 0).sum()

np.int64(48)

In [72]:
bools = np.array([False, True, False, True, False])

In [73]:
bools.any()

np.True_

In [74]:
bools.all()

np.False_