In [8]:
import numpy as np


In [10]:
rng = np.random.default_rng() 

In [11]:
arr = rng.standard_normal(6)

In [12]:
arr

array([ 0.88977267,  0.4617568 ,  1.65248152, -0.5127987 ,  0.07178013,
        1.39485179])

In [13]:
arr.sort()

In [14]:
arr

array([-0.5127987 ,  0.07178013,  0.4617568 ,  0.88977267,  1.39485179,
        1.65248152])

In [15]:
arr = rng.standard_normal((5,3))

In [16]:
arr

array([[ 0.52515065, -0.92677232, -0.11978785],
       [ 1.14353186,  0.5985227 , -0.59460248],
       [ 0.43902924,  0.40452997, -1.19578401],
       [ 1.72137129, -0.61510183, -0.12565657],
       [-0.16256877, -0.13067647, -0.15970616]])

In [19]:
arr.sort(axis = 0)

In [20]:
arr

array([[-1.19578401, -0.15970616, -0.13067647],
       [-0.92677232, -0.12565657,  0.43902924],
       [-0.61510183, -0.11978785,  0.52515065],
       [-0.59460248,  0.40452997,  1.14353186],
       [-0.16256877,  0.5985227 ,  1.72137129]])

In [21]:
arr.sort(axis = 1)

In [22]:
arr

array([[-1.19578401, -0.15970616, -0.13067647],
       [-0.92677232, -0.12565657,  0.43902924],
       [-0.61510183, -0.11978785,  0.52515065],
       [-0.59460248,  0.40452997,  1.14353186],
       [-0.16256877,  0.5985227 ,  1.72137129]])

In [25]:
arr2 = np.array([5,-10,7,1,0,-3])

In [27]:
sorted_arr2 = np.sort(arr2)

In [28]:
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

In [32]:
names = np.array(["ahem", "x", "y", "x", "bpb", "y"])

In [33]:
np.unique(names)

array(['ahem', 'bpb', 'x', 'y'], dtype='<U4')

In [34]:
sorted(set(names))

[np.str_('ahem'), np.str_('bpb'), np.str_('x'), np.str_('y')]

In [35]:
values = np.array([6,0,0,3,2,5,6])

In [38]:
import numpy as np

In [40]:
np.isin(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [41]:
arr = np.arange(10)

In [42]:
np.save("some_array", arr)

In [44]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.savez("array_archive.npz", a = arr, b = arr)

In [47]:
arch = np.load("array_archive.npz")

In [48]:
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])

In [50]:
y = np.array([[6.,23.],[-1,7],[8, 9]])

In [51]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [52]:
from numpy.linalg import inv, qr

In [54]:
x = rng.standard_normal((5,5))

In [55]:
mat = x.T @ x

In [56]:
inv(mat)

array([[  0.65557136,   2.29774866,   3.1635274 ,   0.50870009,
         -5.08828392],
       [  2.29774866,   9.8042344 ,  12.70774818,   2.02618033,
        -21.3503573 ],
       [  3.1635274 ,  12.70774818,  17.25989533,   2.79575382,
        -28.35788956],
       [  0.50870009,   2.02618033,   2.79575382,   0.52615407,
         -4.73642845],
       [ -5.08828392, -21.3503573 , -28.35788956,  -4.73642845,
         48.3369917 ]])

In [57]:
mat @ inv(mat)

array([[ 1.00000000e+00, -1.36340827e-15, -5.32100206e-15,
        -4.00346806e-16, -6.28308320e-15],
       [ 9.06095097e-16,  1.00000000e+00, -4.21609966e-16,
        -9.22996005e-16, -2.17670431e-15],
       [ 9.43296919e-16,  8.77840062e-15,  1.00000000e+00,
         7.23007466e-16, -1.21950559e-15],
       [ 2.60972538e-15, -1.34126309e-16, -7.83421046e-15,
         1.00000000e+00, -1.16700463e-14],
       [ 1.18210083e-16, -2.19741982e-15, -1.58518570e-15,
        -9.98581880e-17,  1.00000000e+00]])

In [58]:
import random

In [59]:
nsteps = 1000

In [60]:
rng = np.random.default_rng(seed = 12345)

In [61]:
draws = rng.integers(0,2, size = nsteps)

In [63]:
steps = np.where(draws == 0, 1, -1)

In [64]:
walk = steps.cumsum()

In [65]:
walk.min()

np.int64(-8)

In [66]:
walk.max()

np.int64(50)