In [1]:
import numpy as np

In [2]:
data = np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
data * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
data + data

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [6]:
data.shape

(2, 4)

In [7]:
data.dtype

dtype('int64')

In [8]:
data1 = [1,-3,7.6,5,0]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([ 1. , -3. ,  7.6,  5. ,  0. ])

In [18]:
data2 = [[2,4,3,1],[76,5,-9,0]]

In [19]:
arr2 = np.array(data2)

In [20]:
arr2

array([[ 2,  4,  3,  1],
       [76,  5, -9,  0]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.empty((2,3, 2))

array([[[1.35556896e-311, 2.42092166e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.58817677e-052]],

       [[7.43241589e-091, 5.73900878e+174],
        [6.54511889e-043, 1.78603877e-051],
        [6.99196247e+228, 7.56504748e-067]]])

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
arr = np.arange(10)

In [39]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5:8]

array([5, 6, 7])

In [42]:
arr[5:8] = 12

In [43]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [44]:
arr_slice = arr[5:8]

In [45]:
arr_slice[1] = 1234

In [46]:
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [47]:
arr3d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [48]:
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [49]:
arr3d[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
arr3d[0] = 42

In [51]:
arr3d

array([[[42, 42, 42, 42],
        [42, 42, 42, 42]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [52]:
names = np.array(["bob", "joe", "will", "bob", "will", "joe", "joe"])

In [53]:
data = np.array([[4,0],[5,6],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])

In [54]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [55]:
data

array([[  4,   0],
       [  5,   6],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [56]:
names == "bob"

array([ True, False, False,  True, False, False, False])

In [57]:
data[names == "bob"]

array([[4, 0],
       [0, 0]])

In [58]:
data[names == "bob" , 1:]

array([[0],
       [0]])

In [59]:
data[names == "bob", 1]

array([0, 0])

In [60]:
arr = np.zeros((8,4))

In [62]:
for i in range(8):
    arr[i] = i

In [63]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [64]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [66]:
arr = np.arange(15).reshape((3,5))

In [67]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])